services:
  data-streams:
    container_name: data-streams
    build:
      context: .
      dockerfile: ./apps/data-streams/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./:/app/data-streams
      - /app/data-streams/node_modules
    command: ['yarn', 'dev:data-streams']
    networks:
      - weld
    depends_on:
      - worker
      - rabbitmq
      - mongodb

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    ports:
      - 3002:3002
    volumes:
      - ./:/app/worker
      - /app/worker/node_modules
    command: ['yarn', 'dev:worker']
    depends_on:
      - rabbitmq
    networks:
      - weld

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - weld

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    networks:
      - weld

networks:
  weld:
