services:
  data-streams:
    container_name: data-streams
    build:
      context: .
    ports:
      - '3001:3001'
    networks:
      - weld
    depends_on:
      - worker
      - rabbitmq
      - mongodb

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    ports:
      - '3002:3002'
    depends_on:
      - rabbitmq
    networks:
      - weld

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - weld

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - weld

networks:
  weld:
